import { useState, useEffect } from 'react';
import { gitAPI } from '../../services/api';
import InputDialog from '../InputDialog';
import { 
  GitPullRequest, RefreshCw, Loader2, CheckCircle, FileText, 
  X, ExternalLink 
} from 'lucide-react';

interface SourceControlPanelProps {
    projectId: number;
}

export default function SourceControlPanel({ projectId }: SourceControlPanelProps) {
  const [changes, setChanges] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [prLoading, setPrLoading] = useState(false);
  
  // PR Form State
  const [prTitle, setPrTitle] = useState('');
  const [prDesc, setPrDesc] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [showTokenDialog, setShowTokenDialog] = useState(false);

  // Success Dialog State
  const [prSuccess, setPrSuccess] = useState<{ isOpen: boolean; url: string; branch: string } | null>(null);

  const refreshStatus = async () => {
    setLoading(true);
    try {
      const res = await gitAPI.getStatus(projectId);
      const allChanges = [...(res.data.changes || []), ...(res.data.staged || [])];
      const unique = Array.from(new Map(allChanges.map(item => [item.path, item])).values());
      setChanges(unique);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { refreshStatus(); }, [projectId]);

  const generatePrMessage = async () => {
      if (changes.length === 0) return;
      setIsGenerating(true);
      setTimeout(() => {
         setPrTitle(`Update ${changes.length} files: ${changes.slice(0, 2).map(c => c.name).join(', ')}`);
         setPrDesc(`Automated update generated by Ubiq Editor.\n\nChanged Files:\n- ${changes.map(c => c.name).join('\n- ')}`);
         setIsGenerating(false);
      }, 600);
  };

  const handlePrClick = () => {
      const stored = localStorage.getItem('ubiq_api_keys');
      if (stored) {
          try {
              const keys = JSON.parse(stored);
              if (keys.github) {
                  executeCreatePr(keys.github);
                  return;
              }
          } catch(e) {}
      }
      setShowTokenDialog(true);
  };

  const executeCreatePr = async (token: string) => {
      setPrLoading(true);
      try {
          const res = await gitAPI.createPr(projectId, {
              token,
              title: prTitle || "Update from Ubiq",
              description: prDesc || "Automated update."
          });
          
          // SUCCESS: Clear form, refresh, and show Custom Dialog
          setPrTitle('');
          setPrDesc('');
          refreshStatus();
          
          // Show Nice Success Modal
          setPrSuccess({
              isOpen: true,
              url: res.data.pr_url,
              branch: res.data.branch || 'unknown-branch'
          });
          
          const stored = localStorage.getItem('ubiq_api_keys');
          const keys = stored ? JSON.parse(stored) : {};
          localStorage.setItem('ubiq_api_keys', JSON.stringify({ ...keys, github: token }));

      } catch (e: any) {
          // Use a simple alert for errors, or you can add an Error Dialog state too
          alert("Failed to create PR: " + (e.response?.data?.error || e.message));
      } finally {
          setPrLoading(false);
          setShowTokenDialog(false);
      }
  };

  return (
    <div className="flex flex-col h-full bg-ubiq-950 border-r border-white/5 w-72 select-none relative">
      
      {/* Header */}
      <div className="p-4 border-b border-white/5 flex items-center justify-between bg-ubiq-900/50">
        <h2 className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
            Review Changes
        </h2>
        <button onClick={refreshStatus} className="text-slate-500 hover:text-white transition-colors p-1" title="Refresh Status">
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Changes List */}
      <div className="flex-1 overflow-y-auto p-2">
          {changes.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-40 text-slate-600 space-y-2">
                  <CheckCircle className="w-8 h-8 opacity-20" />
                  <p className="text-xs">No changes detected</p>
              </div>
          ) : (
              <div className="space-y-1">
                  <div className="px-2 pb-2 text-[10px] font-bold text-slate-500 uppercase flex justify-between">
                      <span>Modified Files</span>
                      <span className="bg-white/10 px-1.5 rounded text-slate-300">{changes.length}</span>
                  </div>
                  {changes.map(file => (
                      <div key={file.path} className="flex items-center gap-2 px-3 py-2 bg-white/5 hover:bg-white/10 rounded text-xs text-slate-300 transition-colors cursor-default">
                          <FileText className="w-3.5 h-3.5 text-blue-400 opacity-80" />
                          <span className="truncate" title={file.path}>{file.name}</span>
                          <span className={`ml-auto text-[9px] font-bold ${file.status === 'NEW' ? 'text-green-500' : 'text-yellow-500'}`}>
                              {file.status}
                          </span>
                      </div>
                  ))}
              </div>
          )}
      </div>

      {/* PR Form Area */}
      <div className="p-4 border-t border-white/5 bg-ubiq-900/30 space-y-3">
          <div className="flex justify-between items-center">
             <label className="text-[10px] font-bold text-slate-500 uppercase">PR Details</label>
             <button 
                onClick={generatePrMessage}
                disabled={changes.length === 0 || isGenerating}
                className="text-[10px] text-indigo-400 hover:text-indigo-300 flex items-center gap-1 transition-colors"
             >
                 {isGenerating ? <Loader2 className="w-3 h-3 animate-spin"/> : "✨ Auto-Generate"}
             </button>
          </div>

          <input 
            value={prTitle}
            onChange={e => setPrTitle(e.target.value)}
            placeholder="PR Title (e.g. Fixed Navbar)"
            className="w-full bg-black/30 border border-white/10 rounded px-2 py-2 text-xs text-white focus:border-indigo-500 outline-none transition-colors"
          />
          
          <textarea 
            value={prDesc}
            onChange={e => setPrDesc(e.target.value)}
            placeholder="Description of changes..."
            className="w-full bg-black/30 border border-white/10 rounded px-2 py-2 text-xs text-white focus:border-indigo-500 outline-none resize-none h-16 transition-colors"
          />

          <button 
            onClick={handlePrClick}
            disabled={changes.length === 0 || !prTitle || prLoading}
            className="w-full bg-green-600 hover:bg-green-500 disabled:opacity-50 disabled:hover:bg-green-600 text-white text-xs font-bold py-2.5 rounded flex items-center justify-center gap-2 transition-all shadow-lg shadow-green-900/20 active:scale-[0.98]"
          >
            {prLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin"/> : <GitPullRequest className="w-3.5 h-3.5" />} 
            Create Pull Request
          </button>
      </div>

      {/* --- MODALS --- */}

      {/* 1. Token Input */}
      <InputDialog 
        isOpen={showTokenDialog}
        onClose={() => setShowTokenDialog(false)}
        onSubmit={(token) => executeCreatePr(token)}
        title="GitHub Token Required"
        message="Enter a Personal Access Token (classic) with 'repo' scope."
        placeholder="ghp_xxxxxxxxxxxx"
        isPassword={true}
      />

      {/* 2. Success Modal (Custom) */}
      {prSuccess && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
            <div className="bg-ubiq-900 border border-white/10 rounded-xl shadow-2xl w-full max-w-sm overflow-hidden">
                <div className="p-6 text-center space-y-4">
                    <div className="w-12 h-12 bg-green-500/10 rounded-full flex items-center justify-center mx-auto">
                        <CheckCircle className="w-6 h-6 text-green-500" />
                    </div>
                    
                    <div>
                        <h3 className="text-lg font-bold text-white mb-1">Pull Request Created!</h3>
                        <p className="text-xs text-slate-400">
                            Your changes have been pushed to branch: <br/>
                            <code className="text-indigo-300 bg-white/5 px-1.5 py-0.5 rounded mt-1 inline-block">{prSuccess.branch}</code>
                        </p>
                    </div>

                    <div className="flex gap-3 pt-2">
                        <button 
                            onClick={() => setPrSuccess(null)}
                            className="flex-1 px-4 py-2 rounded-lg border border-white/10 text-slate-300 hover:bg-white/5 text-xs font-medium transition-colors"
                        >
                            Close
                        </button>
                        <a 
                            href={prSuccess.url} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="flex-1 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition-colors flex items-center justify-center gap-2"
                            onClick={() => setPrSuccess(null)}
                        >
                            View on GitHub <ExternalLink className="w-3 h-3" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
      )}

    </div>
  );
}