<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Models\UserGithubToken;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;

/**
 * F3 (PLAN_SYSTEM_TASKS.md Phase F, roadmap section F3): GitHub OAuth,
 * replacing pasted Personal Access Tokens for Source Control (see
 * migration 2026_08_09_000004 and UserGithubToken).
 *
 * Deliberately NOT modeled on AuthController's Google flow 1:1: Google
 * OAuth there is a *login* method — it creates or finds a Ubiq account
 * and issues a fresh Sanctum token, so there's no existing session to
 * preserve across the redirect. This flow is the opposite: the user is
 * already logged into Ubiq and is *connecting* a second, separate
 * account (GitHub) to their existing one. A plain
 * `Socialite::driver('github')->stateless()->redirect()` has no way to
 * carry "which logged-in Ubiq user is this?" through a full-page
 * browser navigation to github.com and back — there's no Authorization
 * header on that hop.
 *
 * The fix: a short-lived, single-use "connect ticket" (same Cache-based
 * code-exchange idiom AuthController::handleGoogleCallback already uses
 * for its own callback→token handoff), generated by an authenticated
 * endpoint and threaded through GitHub's own `state` query parameter,
 * which GitHub round-trips back to us unmodified. The ticket is looked
 * up (not GitHub's CSRF state — this literally *is* our CSRF state,
 * generated fresh per attempt, single-use via Cache::pull) to recover
 * the Ubiq user id in callback(), without ever needing a session or
 * relying on Socialite's own (session-based, and therefore SPA-hostile)
 * state handling.
 */
class GithubOAuthController extends Controller
{
    private const SCOPES = ['repo'];

    /**
     * POST /auth/github/connect — authenticated (Sanctum). Returns a
     * one-time URL the frontend should navigate the browser to (a full
     * page nav, e.g. `window.location.href = url` — not an axios call,
     * this has to actually leave the SPA and land on github.com).
     */
    public function connect(Request $request)
    {
        // GITHUB_CLIENT_ID has no fallback default (unlike
        // GITHUB_REDIRECT_URI just below, which does) — if it's unset
        // or the config cache predates it being added to .env,
        // `config('services.github.client_id')` silently resolves to
        // null/empty, and GitHub's own /login/oauth/authorize endpoint
        // returns a bare 404 page for a missing/empty client_id (this
        // is documented GitHub behavior, not specific to this app —
        // it can't tell a blank client_id from "no such app exists").
        // Without this guard the failure surfaces as an inexplicable
        // GitHub 404 with zero context; fail fast here instead, before
        // ever sending the browser to github.com.
        if (empty(config('services.github.client_id')) || empty(config('services.github.client_secret'))) {
            Log::error('[GithubOAuth] connect() called but GITHUB_CLIENT_ID/GITHUB_CLIENT_SECRET are not configured on this server.');
            return response()->json([
                'error' => 'github_not_configured',
                'message' => 'GitHub connection isn\'t configured on this server yet. Set GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET (see .env.example) and clear the config cache, or paste a repository URL manually for now.',
            ], 503);
        }

        $ticket = Str::random(40);
        Cache::put("github_connect:{$ticket}", $request->user()->id, now()->addMinutes(10));

        $params = http_build_query([
            'client_id'    => config('services.github.client_id'),
            'redirect_uri' => config('services.github.redirect'),
            'scope'        => implode(' ', self::SCOPES),
            'state'        => $ticket,
            'allow_signup' => 'false',
        ]);

        return response()->json([
            'redirect_url' => "https://github.com/login/oauth/authorize?{$params}",
        ]);
    }

    /**
     * GET /auth/github/callback — public (GitHub lands the browser here
     * directly; there's no Ubiq bearer token available on this request).
     * Identity is recovered entirely from the `state` ticket minted in
     * connect() above, not from any auth header or session.
     */
    public function callback(Request $request)
    {
        $frontendUrl = env('FRONTEND_URL', 'https://ubiq-editor.space');
        $state = $request->query('state');

        if (!$state) {
            return redirect("{$frontendUrl}/settings?github_error=missing_state");
        }

        // Single-use: pull deletes the ticket as it reads it, so a
        // replayed callback URL (or two tabs racing) can't attach the
        // same connect attempt to two different outcomes.
        $userId = Cache::pull("github_connect:{$state}");

        if (!$userId) {
            return redirect("{$frontendUrl}/settings?github_error=expired_or_invalid_state");
        }

        try {
            $githubUser = Socialite::driver('github')->stateless()->user();

            UserGithubToken::updateOrCreate(
                ['user_id' => $userId],
                [
                    'access_token'      => $githubUser->token,
                    'github_username'   => $githubUser->getNickname() ?? $githubUser->getName(),
                    'github_avatar_url' => $githubUser->getAvatar(),
                    // Socialite exposes the granted scopes GitHub actually
                    // returned (can differ from what was requested if the
                    // user or org restricts them) via getApprovedScopes()
                    // on the GitHub provider.
                    'scopes'            => method_exists($githubUser, 'getApprovedScopes')
                        ? implode(',', $githubUser->getApprovedScopes() ?? [])
                        : implode(',', self::SCOPES),
                    'connected_at'      => now(),
                ]
            );

            return redirect("{$frontendUrl}/settings?github_connected=1");

        } catch (\Exception $e) {
            Log::error('[GithubOAuth] callback failed: ' . $e->getMessage());
            return redirect("{$frontendUrl}/settings?github_error=connection_failed");
        }
    }

    /**
     * GET /user/github — authenticated. Whether this user has a GitHub
     * connection and, if so, the non-secret bits worth showing in
     * Settings. Never returns the token itself (UserGithubToken hides
     * it, and this doesn't touch that field at all).
     */
    public function status(Request $request)
    {
        $token = UserGithubToken::where('user_id', $request->user()->id)->first();

        if (!$token) {
            return response()->json(['connected' => false]);
        }

        return response()->json([
            'connected'    => true,
            'username'     => $token->github_username,
            'avatar_url'   => $token->github_avatar_url,
            'connected_at' => $token->connected_at,
            'last_used_at' => $token->last_used_at,
        ]);
    }

    /**
     * DELETE /user/github — authenticated. Revokes the stored token
     * outright (not a soft-delete), same idempotent-204 shape as
     * AiKeyController::destroy(). Deliberately does NOT call GitHub's
     * own token-revocation API — the OAuth App's access is left valid
     * on GitHub's side (the user can review/revoke it themselves from
     * github.com/settings/applications) while Ubiq simply forgets the
     * token; calling it here would need the OAuth App's client secret
     * on every disconnect for marginal benefit over "we just stopped
     * being able to use it."
     */
    public function disconnect(Request $request)
    {
        UserGithubToken::where('user_id', $request->user()->id)->delete();

        return response()->json(null, 204);
    }

    /**
     * GET /user/github/repos — authenticated.
     *
     * F3e (PLAN_SYSTEM_TASKS.md Phase F): the repo picker this powers
     * replaces "paste a repo URL by hand" in CreateProjectDialog.tsx
     * with a searchable list of repos the connected account can
     * actually see — using the real OAuth token's granted scopes
     * (`repo`, from self::SCOPES above) rather than a second manual
     * PAT paste. `store()`/`importFromGithub()` in ProjectController
     * are untouched by this: they already accept a plain
     * `repository_url` string and already prefer the stored OAuth
     * token over a pasted one (see F3c) — this endpoint only needs to
     * *supply* that URL, not change how it's consumed.
     *
     * GitHub's `GET /user/repos` is the right endpoint rather than
     * `GET /user/starred` or the search API: it returns every repo the
     * token's scopes grant access to — owned, collaborator, and org
     * repos — which matches "what could this user plausibly want to
     * import", not just what they personally own.
     *
     * Client-side search/filter (same pattern as the Sandboxes list
     * page) rather than a server-side `q=` search param: GitHub's own
     * repo *search* API is a different, separately-rate-limited
     * endpoint with its own query syntax, and paginating "all repos
     * this token can see, most recently updated first" already gives
     * the frontend everything it needs to filter locally without a
     * second network round-trip per keystroke.
     */
    public function repos(Request $request)
    {
        $token = UserGithubToken::where('user_id', $request->user()->id)->first();

        if (!$token) {
            return response()->json([
                'error' => 'not_connected',
                'message' => 'Connect your GitHub account first.',
            ], 409);
        }

        try {
            $repos = [];
            // GitHub caps per_page at 100; walk a few pages so an active
            // account's less-recently-touched repos still show up in the
            // picker without needing every repo they've ever made. 300
            // covers the overwhelming majority of individual/small-org
            // accounts this product targets; a "load more" flow would be
            // the honest next step past that, not fetching unbounded pages
            // synchronously inside one request.
            for ($page = 1; $page <= 3; $page++) {
                $response = Http::withToken($token->access_token)
                    ->withHeaders(['Accept' => 'application/vnd.github+json'])
                    ->timeout(15)
                    ->get('https://api.github.com/user/repos', [
                        'per_page' => 100,
                        'page' => $page,
                        'sort' => 'updated',
                        'affiliation' => 'owner,collaborator,organization_member',
                    ]);

                if ($response->status() === 401) {
                    // Token revoked on GitHub's side (user removed the
                    // OAuth App grant, rotated it, etc.) without going
                    // through Ubiq's own disconnect() — surface that
                    // distinctly so the frontend can prompt reconnect
                    // instead of showing a generic error.
                    return response()->json([
                        'error' => 'token_invalid',
                        'message' => 'Your GitHub connection has expired or been revoked. Please reconnect.',
                    ], 401);
                }

                if (!$response->successful()) {
                    Log::error('[GithubOAuth] repos() GitHub API error', [
                        'user_id' => $request->user()->id,
                        'status' => $response->status(),
                        'body' => $response->body(),
                    ]);
                    return response()->json([
                        'error' => 'github_api_error',
                        'message' => 'GitHub API request failed. Please try again in a moment.',
                    ], 502);
                }

                $page_data = $response->json();
                if (empty($page_data)) {
                    break;
                }
                $repos = array_merge($repos, $page_data);
                if (count($page_data) < 100) {
                    break; // last page
                }
            }

            $token->update(['last_used_at' => now()]);

            return response()->json([
                'repos' => collect($repos)->map(fn (array $r) => [
                    'name' => $r['name'],
                    'full_name' => $r['full_name'],
                    'html_url' => $r['html_url'],
                    'clone_url' => $r['clone_url'],
                    'private' => $r['private'],
                    'default_branch' => $r['default_branch'] ?? 'main',
                    'description' => $r['description'],
                    'language' => $r['language'],
                    'updated_at' => $r['updated_at'],
                    'owner_login' => $r['owner']['login'] ?? null,
                    'owner_avatar_url' => $r['owner']['avatar_url'] ?? null,
                ])->values(),
            ]);

        } catch (\Exception $e) {
            Log::error('[GithubOAuth] repos() failed: ' . $e->getMessage());
            return response()->json([
                'error' => 'github_api_error',
                'message' => 'Could not load your repositories. Please try again.',
            ], 502);
        }
    }
}
