import React, { useState } from 'react';
import axios from 'axios';

export const UpgradeButton: React.FC = () => {
    const [loading, setLoading] = useState(false);

    const handleUpgrade = async () => {
        setLoading(true);
        try {
            // 1. Get the Pay Link from your Laravel backend
            const response = await axios.get('/api/v1/auth/pay-link', {
                headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
            });

            // 2. Open Paddle Checkout
            // @ts-ignore (Paddle is loaded via CDN)
            window.Paddle.Checkout.open({
                settings: {
                    displayMode: 'overlay',
                    theme: 'dark',
                    locale: 'en'
                },
                // Use the URL generated by Cashier
                checkoutUrl: response.data 
            });
        } catch (error) {
            console.error("Failed to start checkout:", error);
            alert("Could not initialize payment. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <button 
            onClick={handleUpgrade}
            disabled={loading}
            className="bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2 rounded-lg font-bold transition"
        >
            {loading ? 'Initializing...' : 'Upgrade to Pro'}
        </button>
    );
};